// https://pspdfkit.com/blog/2019/visual-studio-code-for-cpp/

// CMakeLists.txt is generated by the CMake Tools Extension
// https://vector-of-bool.github.io/docs/vscode-cmake-tools/index.html

// http://cplusplus.com/forum/beginner/157663/

#include <iostream>
#include "box.h"
using namespace std;

int main()
{
    double length;
    double width;
    double height;
    double volume;
    Box box;

    cout << "Please Enter a Length for your box: ";
    cin >> length;
    box.setLength(length);
    cout << "Please Enter a Width for your box: ";
    cin >> width;
    box.setWidth(width);
    cout << "Please Enter a Height for your box: ";
    cin >> height;
    box.setHeight(height);
    //cout << "\n\n" << box.getParameters();
    volume = box.getVolume();
    cout << "\n\nThe Volume of your box is: " << volume;
    box.getParameters();
    return 0;
}
