// https://pspdfkit.com/blog/2019/visual-studio-code-for-cpp/

// CMakeLists.txt is generated by the CMake Tools Extension
// https://vector-of-bool.github.io/docs/vscode-cmake-tools/index.html

#include <iostream>

int main(int, char**) {
    std::cout << "\nHello, world!\n\n\n";
}
